name: .NET - Build and Test

on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory containing the .NET solution
        type: string
        required: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ${{ inputs.working-directory }}

      - name: Run Tests
        run: dotnet test --no-restore --logger trx --results-directory TestResults
        working-directory: ${{ inputs.working-directory }}

      - name: Test Summary
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Tests
          path: ${{ inputs.working-directory }}/TestResults/*.trx
          reporter: dotnet-trx

      - name: Build
        run: dotnet build --no-restore
        working-directory: ${{ inputs.working-directory }}
